source: .
destination: _deploy
url: https://ocf.tw
# defaults:
#   - scope:
#       path: ""
#     values:
#       og_title: "test default title"
#       og_image: /mediakit/cover.png
#       og_description: "test default description"
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
encoding: utf-8
